### PR TITLE
Add compatibiliy with the jail plugin

### PR DESCRIPTION
**Pull request by Cuhnt**
A simple reflection addition to make Jailed players not leave a PvPLog skeleton

### CODE REVIEW

**Comment by Cuhnt** [comment]
I just marked this as a draft because I have been running into issues with reflection. Even getting the set through the field every time has been returning an empty set. 
My tests seemed to work because I was doing them within the plugin's "spawn area" without realizing. I have since changed that, and am currently working on figuring out why the reflection is not working as it should.
This should not be merged yet,

**Comment by C4K3** [comment]
I believe this change does work, it just needs this commit https://github.com/C4K3/Jail/commit/254a79a4bb5754f4e88b30d0f620f12ab695fc69

Without ^ the Jail plugin's PlayerQuit handler was apparently getting triggered before AntiPvPLog, which is why the list was showing as empty when the AntiPvPLog handler ran.

**Comment by Melvin3000** [comment]
So this is ready to merge then? 

edit: Looking at it does JAILED_MAP ever get updated (reference vs copy?) if a new player is jailed after init?

**Comment by C4K3** [comment]
It should be ready. It does appear to just be a reference rather than deep clone. This patch is currently running on the build server if you want to test it there.

**Comment by Melvin3000** [comment]
Ok cool. Thanks

**Pull request merged**
